
export const FOOD_TYPE = [{
        title: '生鮮雜貨',
        icon: 'https://cn-geo1.uber.com/static/mobile-content/eats/cuisine-filters/Grocery.png'
    }, {
        title: '珍珠奶茶',
        icon: 'https://cn-geo1.uber.com/static/mobile-content/eats/cuisine-filters/v1/BubbleTea.png'
    }, {
        title: '台灣美食',
        icon: 'https://cn-geo1.uber.com/static/mobile-content/eats/cuisine-filters/v1/Taiwanese.png'
    }, {
        title: '中式美食',
        icon: 'https://cn-geo1.uber.com/static/mobile-content/eats/cuisine-filters/v1/Chinese.png'
    }, {
        title: '速食',
        icon: 'https://cn-geo1.uber.com/static/mobile-content/eats/cuisine-filters/v1/FastFood.png'
    }, {
        title: '義大利美食',
        icon: 'https://cn-geo1.uber.com/static/mobile-content/eats/cuisine-filters/v1/Italian.png'
    }, {
        title: '甜點',
        icon: 'https://cn-geo1.uber.com/static/mobile-content/eats/cuisine-filters/v1/Dessert.png'
    }, {
        title: '亞洲美食',
        icon: 'https://cn-geo1.uber.com/static/mobile-content/eats/cuisine-filters/v1/Asian.png'
    }, {
        title: '健康飲食',    
        icon: 'https://cn-geo1.uber.com/static/mobile-content/eats/cuisine-filters/v1/Healthy.png'
    }, {    
        title: '日本美食',
        icon: 'https://cn-geo1.uber.com/static/mobile-content/eats/cuisine-filters/v1/Japanese.png'
    }, {
        title: '漢堡',
        icon: 'https://cn-geo1.uber.com/static/mobile-content/eats/cuisine-filters/v1/Burgers.png'
    }, {
        title: '披薩',
        icon: 'https://cn-geo1.uber.com/static/mobile-content/eats/cuisine-filters/v1/Pizza.png'
    }, {
        title: '韓國美食',
        icon: 'https://cn-geo1.uber.com/static/mobile-content/eats/cuisine-filters/v1/Korean.png'
    }, {
        title: '冰淇淋',
        icon: 'https://cn-geo1.uber.com/static/mobile-content/eats/cuisine-filters/v1/IceCream.png'
    }, {
        title: '美式料理',
        icon: 'https://cn-geo1.uber.com/static/mobile-content/eats/cuisine-filters/v1/American.png'
    }, {
        title: '泰國美食',
        icon: 'https://cn-geo1.uber.com/static/mobile-content/eats/cuisine-filters/v1/Thai.png'
    }, {
        title: '越南美食',
        icon: 'https://cn-geo1.uber.com/static/mobile-content/eats/cuisine-filters/v1/Vietnamese.png'
    }, {
        title: '沙拉',
        icon: 'https://cn-geo1.uber.com/static/mobile-content/eats/cuisine-filters/v1/Salad.png'
    }, {
        title: '三明治',
        icon: 'https://cn-geo1.uber.com/static/mobile-content/eats/cuisine-filters/v1/Sandwich.png'
    }, {
        title: '冰沙',
        icon: 'https://cn-geo1.uber.com/static/mobile-content/eats/cuisine-filters/v1/Smoothie.png'
    }, {
        title: '湯品',
        icon: 'https://cn-geo1.uber.com/static/mobile-content/eats/cuisine-filters/v1/Soup.png'
    }, {
        title: '咖啡',
        icon: 'https://cn-geo1.uber.com/static/mobile-content/eats/cuisine-filters/v1/Coffee.png'
    }, {
        title: '早餐',
        icon: 'https://cn-geo1.uber.com/static/mobile-content/eats/cuisine-filters/v1/Breakfast.png'
    }, {
        title: '街頭美食',
        icon: 'https://cn-geo1.uber.com/static/mobile-content/eats/cuisine-filters/v1/StreetFood.png'
    }, {
        title: 'BBQ',
        icon: 'https://cn-geo1.uber.com/static/mobile-content/eats/cuisine-filters/v1/BBQ.png'
    }, {
        title: '純素料理',
        icon: 'https://cn-geo1.uber.com/static/mobile-content/eats/cuisine-filters/v1/Vegan.png'
    }, {
        title: '療癒美食',
        icon: 'https://cn-geo1.uber.com/static/mobile-content/eats/cuisine-filters/v1/Comfort.png'
    }
];